# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-07 14:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('de_locatie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='aangemaakt')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='gewijzigd')),
                ('sites', models.ManyToManyField(related_name='de_locatie_projecten', to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'Projecten',
                'ordering': ['title'],
                'permissions': (('view_project', 'Can view project'),),
            },
        ),
    ]
