# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-07 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_locatie', '0003_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sites',
        ),
        migrations.AddField(
            model_name='project',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.PositiveIntegerField(choices=[(1, 'De Locatie'), (2, 'Effect Festival')], default=1),
            preserve_default=False,
        ),
    ]
