# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-07 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_locatie', '0004_auto_20170807_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='website',
        ),
        migrations.AddField(
            model_name='project',
            name='visible_effect',
            field=models.BooleanField(default=False, verbose_name='Effect website'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='visible_locatie',
            field=models.BooleanField(default=False, verbose_name='De Locatie website'),
            preserve_default=False,
        ),
    ]
