# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-07 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0059_remove_entiteit_slug'),
        ('de_locatie', '0005_auto_20170807_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maakdenbosch.Entiteit', verbose_name='entiteit'),
        ),
        migrations.AddField(
            model_name='project',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maakdenbosch.Persoon', verbose_name='persoon'),
        ),
        migrations.AlterField(
            model_name='project',
            name='visible_effect',
            field=models.BooleanField(verbose_name='Zichtbaar op de website van het Effect Festival'),
        ),
        migrations.AlterField(
            model_name='project',
            name='visible_locatie',
            field=models.BooleanField(verbose_name='Zichtbaar op de website van De Locatie'),
        ),
    ]
