# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_locatie', '0007_auto_20170807_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['position'], 'permissions': (('view_project', 'Can view project'),), 'verbose_name_plural': 'Projecten'},
        ),
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='positie'),
            preserve_default=False,
        ),
    ]
