# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('de_locatie', '0009_auto_20170906_0933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RemoveField(
            model_name='project',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='project',
            name='person',
        ),
        migrations.DeleteModel(
            name='ProjectEntity',
        ),
        migrations.DeleteModel(
            name='ProjectPerson',
        ),
        migrations.RemoveField(
            model_name='section',
            name='page',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
