# Generated by Django 2.0.2 on 2018-10-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_locatie', '0011_auto_20171211_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='naam')),
                ('logo', models.ImageField(upload_to='')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Keurmerk/Certificatie',
                'verbose_name_plural': 'Keurmerken en Certificaties',
            },
        ),
        migrations.AddField(
            model_name='section',
            name='show_certifications',
            field=models.BooleanField(default=False, verbose_name='laat keurmerken en certificaties zien in deze partnersectie'),
        ),
        migrations.AlterField(
            model_name='section',
            name='show_partners',
            field=models.BooleanField(default=False, verbose_name='laat fondsen zien in deze partnersectie'),
        ),
        migrations.AlterField(
            model_name='section',
            name='show_sponsors',
            field=models.BooleanField(default=False, verbose_name='laat sponsors zien in deze partnersectie'),
        ),
    ]
