# Generated by Django 2.0.2 on 2019-01-18 12:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('de_locatie', '0012_auto_20181010_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='datum')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='foto')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='inhoud')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='de_locatie.Project')),
            ],
            options={
                'verbose_name': 'Agenda-item',
                'verbose_name_plural': 'Agenda-items',
                'ordering': ['-date'],
            },
        ),
    ]
