# Generated by Django 2.0.2 on 2019-02-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_locatie', '0014_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True, help_text='Plak hier een externe link naar het nieuwsbericht', verbose_name='URL'),
        ),
    ]
