# Generated by Django 2.0.2 on 2019-05-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_locatie', '0015_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Normaal'), (2, 'Video'), (4, 'Nieuws'), (5, 'Projecten'), (6, 'Partners'), (7, 'Foto'), (8, 'Formulier'), (9, 'Agenda')], default=1, verbose_name='soort sectie'),
        ),
    ]
