# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 13:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bijeenkomst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('datum', models.DateTimeField(blank=True)),
                ('adres', models.TextField(blank=True)),
                ('deelnemers', models.ManyToManyField(blank=True, related_name='bijeenkomsten', to=settings.AUTH_USER_MODEL)),
                ('organisator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='georganiseerde_bijeenkomsten', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'bijeenkomsten',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Idee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschrijving', models.CharField(max_length=255)),
                ('deelnemers', models.ManyToManyField(blank=True, related_name='ideeen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ideeën',
                'ordering': ['beschrijving'],
            },
        ),
        migrations.CreateModel(
            name='Speerpunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschrijving', models.CharField(max_length=255)),
                ('woord', models.CharField(max_length=32, verbose_name='In één woord')),
                ('bijeenkomst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speerpunten', to='mijndenbosch.Bijeenkomst')),
            ],
            options={
                'verbose_name_plural': 'speerpunten',
                'ordering': ['woord'],
            },
        ),
        migrations.AddField(
            model_name='idee',
            name='speerpunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideeen', to='mijndenbosch.Speerpunt'),
        ),
    ]
