# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bijeenkomst',
            old_name='organisator',
            new_name='netwerkhouder',
        ),
        migrations.AddField(
            model_name='bijeenkomst',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='noorderbreedte'),
        ),
        migrations.AddField(
            model_name='bijeenkomst',
            name='locatie',
            field=models.CharField(blank=True, max_length=255, verbose_name='naam locatie'),
        ),
        migrations.AddField(
            model_name='bijeenkomst',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='oosterlengte'),
        ),
        migrations.AlterField(
            model_name='bijeenkomst',
            name='adres',
            field=models.TextField(blank=True, verbose_name='adres locatie'),
        ),
        migrations.AlterField(
            model_name='bijeenkomst',
            name='naam',
            field=models.CharField(max_length=255, verbose_name='naam netwerk'),
        ),
    ]
