# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bijeenkomst',
            name='deelnemers',
            field=models.ManyToManyField(blank=True, related_name='deelnames', to='mijndenbosch.Persoon'),
        ),
        migrations.AlterField(
            model_name='persoon',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
