# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0002_auto_20160509_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persoon',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
