# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 15:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mijndenbosch', '0002_auto_20160414_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='bijeenkomst',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_at', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bijeenkomst',
            name='fotograaf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotograaf_at', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bijeenkomst',
            name='gespreksleider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gespreksleider_at', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bijeenkomst',
            name='notulist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notulist_at', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bijeenkomst',
            name='twitteraar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitteraar_at', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bijeenkomst',
            name='deelnemers',
            field=models.ManyToManyField(blank=True, related_name='deelnemer_at', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bijeenkomst',
            name='netwerkhouder',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='netwerkhouder_at', to=settings.AUTH_USER_MODEL),
        ),
    ]
