# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mijndenbosch', '0003_auto_20160414_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idee',
            name='deelnemers',
        ),
        migrations.AddField(
            model_name='idee',
            name='inititatiefnemers',
            field=models.ManyToManyField(blank=True, related_name='initiatiefnemer_van', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idee',
            name='kartrekker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kartrekker_van', to=settings.AUTH_USER_MODEL),
        ),
    ]
