# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0004_auto_20160414_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idee',
            old_name='inititatiefnemers',
            new_name='initiatiefnemers',
        ),
    ]
