# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0004_auto_20160512_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deelname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='bijeenkomst',
            options={'ordering': ['naam'], 'verbose_name_plural': 'bijeenkomsten'},
        ),
        migrations.AlterModelOptions(
            name='taak',
            options={'verbose_name_plural': 'taken'},
        ),
        migrations.RemoveField(
            model_name='bijeenkomst',
            name='deelnemers',
        ),
        migrations.RemoveField(
            model_name='taak',
            name='bijeenkomst',
        ),
        migrations.RemoveField(
            model_name='taak',
            name='persoon',
        ),
        migrations.AddField(
            model_name='deelname',
            name='bijeenkomst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deelnames', to='mijndenbosch.Bijeenkomst'),
        ),
        migrations.AddField(
            model_name='deelname',
            name='persoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deelnames', to='mijndenbosch.Persoon'),
        ),
        migrations.AddField(
            model_name='deelname',
            name='taak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mijndenbosch.Taak'),
        ),
    ]
