# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0005_auto_20160414_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bijeenkomst',
            name='netwerkhouder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='netwerkhouder_at', to=settings.AUTH_USER_MODEL),
        ),
    ]
