# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 09:18
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0005_auto_20160512_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ondersteuning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(help_text='Wat is de rol van de persoon bij dit idee? (Bijvoorbeeld bedenker, kartrekker, betrokkene)', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='idee',
            name='initiatiefnemers',
        ),
        migrations.RemoveField(
            model_name='idee',
            name='kartrekker',
        ),
        migrations.AddField(
            model_name='idee',
            name='woord',
            field=models.CharField(default=' ', max_length=255, verbose_name='In één woord'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idee',
            name='beschrijving',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='ondersteuning',
            name='idee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mijndenbosch.Idee'),
        ),
        migrations.AddField(
            model_name='ondersteuning',
            name='persoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ondersteuningen', to='mijndenbosch.Persoon'),
        ),
    ]
