# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mijndenbosch', '0006_auto_20160414_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['naam'],
                'verbose_name_plural': 'taken',
            },
        ),
        migrations.RemoveField(
            model_name='bijeenkomst',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='bijeenkomst',
            name='fotograaf',
        ),
        migrations.RemoveField(
            model_name='bijeenkomst',
            name='gespreksleider',
        ),
        migrations.RemoveField(
            model_name='bijeenkomst',
            name='netwerkhouder',
        ),
        migrations.RemoveField(
            model_name='bijeenkomst',
            name='notulist',
        ),
        migrations.RemoveField(
            model_name='bijeenkomst',
            name='twitteraar',
        ),
        migrations.AddField(
            model_name='taak',
            name='bijeenkomst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken', to='mijndenbosch.Bijeenkomst'),
        ),
        migrations.AddField(
            model_name='taak',
            name='persoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken', to=settings.AUTH_USER_MODEL),
        ),
    ]
