# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 09:21
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0006_auto_20160512_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idee',
            name='woord',
        ),
        migrations.AddField(
            model_name='idee',
            name='toelichting',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='idee',
            name='beschrijving',
            field=models.CharField(max_length=255),
        ),
    ]
