# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0008_auto_20160512_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ondersteuning',
            options={'verbose_name_plural': 'ondersteuningen'},
        ),
    ]
