# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0009_auto_20160512_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='bijeenkomst',
            name='beschrijving',
            field=models.TextField(blank=True, verbose_name='Karaktereigenschappen'),
        ),
        migrations.AddField(
            model_name='bijeenkomst',
            name='burgermeester',
            field=models.CharField(blank=True, max_length=255, verbose_name='naam burgermeester'),
        ),
        migrations.AddField(
            model_name='bijeenkomst',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ondersteuning',
            name='idee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ondersteuningen', to='mijndenbosch.Idee'),
        ),
    ]
