# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0010_auto_20160512_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idee',
            options={'verbose_name_plural': 'ideeën'},
        ),
        migrations.AlterModelOptions(
            name='speerpunt',
            options={'verbose_name_plural': 'speerpunten'},
        ),
        migrations.AlterField(
            model_name='speerpunt',
            name='beschrijving',
            field=models.TextField(),
        ),
    ]
