# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0011_auto_20160519_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speerpunt',
            old_name='beschrijving',
            new_name='toelichting',
        ),
    ]
