# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0012_auto_20160519_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speerpunt',
            old_name='woord',
            new_name='beschrijving',
        ),
    ]
