# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0016_auto_20160519_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idee',
            options={'ordering': ['pk'], 'verbose_name_plural': 'ideeën'},
        ),
        migrations.AlterModelOptions(
            name='speerpunt',
            options={'ordering': ['pk'], 'verbose_name_plural': 'speerpunten'},
        ),
        migrations.AddField(
            model_name='bijeenkomst',
            name='slug',
            field=models.SlugField(blank=True, help_text='De burgermeester van dit netwerk is ook te bezoeken op mijndenbosch.nl/[watjijhierinvult]/', verbose_name='url'),
        ),
    ]
