# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0018_auto_20160530_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webtekst',
            options={'ordering': ['plek'], 'verbose_name_plural': 'webteksten'},
        ),
    ]
