# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 10:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0020_persoon_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='persoon',
            name='aangemaakt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 9, 10, 16, 45, 450677, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
