# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0021_persoon_aangemaakt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persoon',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='personen', to='sites.Site'),
        ),
    ]
