# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0022_auto_20160609_1556'),
    ]

    # Add custom database_operations
    database_operations = [
        # You have to use Django's database table naming defaults to get the
        # name 'tires_tires'. It is basically <app_name>_<model_name>.
        migrations.AlterModelTable('persoon', 'maakdenbosch_persoon'),
    ]

    # Don't modify the Django 'state' yet
    state_operations = [

    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
