# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0023_auto_20160621_1303'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='persoon',
        #     name='sites',
        # ),
        # migrations.RemoveField(
        #     model_name='persoon',
        #     name='user',
        # ),
        migrations.AlterField(
            model_name='bijeenkomst',
            name='netwerkhouder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bijeenkomsten', to='maakdenbosch.Persoon'),
        ),
        migrations.AlterField(
            model_name='deelname',
            name='persoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deelnames', to='maakdenbosch.Persoon'),
        ),
        migrations.AlterField(
            model_name='ondersteuning',
            name='persoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ondersteuningen', to='maakdenbosch.Persoon'),
        ),
        # migrations.DeleteModel(
        #     name='Persoon',
        # ),
    ]
