# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0024_auto_20160621_1307'),
    ]

    # This needs to be a state-only operation because the database model was
    # renamed, and no longer exists according to Django.
    state_operations = [
        # Pasted from auto-generated operations in previous step:
        migrations.RemoveField(
            model_name='persoon',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='persoon',
            name='user',
        ),
        migrations.DeleteModel(
            name='Persoon',
        ),
    ]

    operations = [
        # After this state operation, the Django DB state should match the 
        # actual database structure.
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
