# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 10:02
from __future__ import unicode_literals

from django.db import migrations, models

def resave_stuff(*args, **kwargs):
    print('Re-saving all speerpunten and ideeen...')
    from mijndenbosch.models import Speerpunt, Idee
    for s in Speerpunt.objects.all():
        s.save()
    for i in Idee.objects.all():
        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0027_auto_20160706_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idee',
            name='nummer',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='speerpunt',
            name='nummer',
            field=models.PositiveIntegerField(),
        ),
        migrations.RunPython(resave_stuff, migrations.RunPython.noop),
    ]
