# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0028_auto_20160706_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taak',
            options={'ordering': ['naam'], 'verbose_name_plural': 'taken'},
        ),
    ]
