# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0029_auto_20160711_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idee',
            name='nummer',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='speerpunt',
            name='nummer',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
