# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0031_auto_20161122_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mayor',
            options={'ordering': ['created', 'name'], 'verbose_name': 'burgeRmeester'},
        ),
        migrations.AddField(
            model_name='mayor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
