# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0032_auto_20161122_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mayor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 22, 13, 54, 1, 639210, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
