# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0033_auto_20161122_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mayor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='aangemeld op'),
        ),
        migrations.AlterField(
            model_name='mayor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mayors', to='maakdenbosch.Persoon', verbose_name='door persoon'),
        ),
    ]
