# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 22:20
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0034_auto_20161122_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['number', 'mayor'], 'verbose_name': 'idee', 'verbose_name_plural': 'ideeën'},
        ),
        migrations.AlterModelOptions(
            name='idee',
            options={'ordering': ['nummer', 'speerpunt'], 'verbose_name': 'idee (oude stijl)', 'verbose_name_plural': 'ideeën (oude stijl)'},
        ),
        migrations.AlterModelOptions(
            name='mayor',
            options={'ordering': ['created', 'name'], 'verbose_name': 'BurgeRmeester'},
        ),
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='beschrijving'),
        ),
    ]
