# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-07 14:00
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0056_auto_20161122_1435'),
        ('mijndenbosch', '0035_auto_20161123_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='bijeenkomst',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='maakdenbosch.Entiteit', verbose_name='entiteit'),
        ),
        migrations.AddField(
            model_name='mayor',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mayors', to='mijndenbosch.Bijeenkomst', verbose_name='door bijeenkomst'),
        ),
        migrations.AlterField(
            model_name='bijeenkomst',
            name='beschrijving',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='beschrijving van de bijeenkomst'),
        ),
        migrations.AlterField(
            model_name='mayor',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mayors', to='maakdenbosch.Persoon', verbose_name='door persoon'),
        ),
    ]
