# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-07 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0040_remove_bijeenkomst_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bijeenkomst',
            name='slug',
            field=models.SlugField(help_text='Deze bijeenkomst is te bezoeken op mijndenbosch.nl/[watjijhierinvult]/', null=True, unique=True, verbose_name='url'),
        ),
    ]
