# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-21 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0044_auto_20161216_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='mayor',
            name='slug',
            field=models.SlugField(help_text='Deze burgermeester is te bezoeken op mijndenbosch.nl/burgermeester/[watjijhierinvult]/', null=True, unique=True, verbose_name='url'),
        ),
    ]
