# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-04 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mijndenbosch', '0045_mayor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mayor',
            name='slug',
            field=models.SlugField(help_text='Deze burgermeester is straks te bezoeken op mijndenbosch.nl/burgermeester/[watjijhierinvult]/', null=True, unique=True, verbose_name='url'),
        ),
    ]
