#!/usr/bin/env python
from fabric.api import *
from fabric.contrib.files import exists
from fabric.colors import red, green

project_name = 'databosch'
env.host_string = 'databosch.created.today'

# Transfer files
print(red('\nTransferring files...', bold=True))
env.user = 'www'
local('rsync -av --delete --exclude graphics ./ %s@%s:%s' % (env.user, env.host_string, project_name))

print(red('\nDisabling debug', bold=True))
run('rm %s/databosch/debug.py' % project_name)

# Initialize virtualenv
print(red('\nCreating Python 3 virtualenv...', bold=True))
if not exists('.virtualenvs/%s' % project_name):
    run('mkvirtualenv -p /usr/bin/python3 %s' % project_name)
with cd(project_name):
    with prefix('workon %s' % project_name):
        run('pip install -r requirements.txt')

        # Django householding
        print(red('\nRunning Django household commands', bold=True))
        run('./manage.py migrate')
        run('mkdir -p /srv/%s' % project_name)
        run('yes yes | ./manage.py collectstatic')

# Place config files
print(red('\n(Re)placing config files...', bold=True))
env.user = 'origin'
put('databosch.ini', '/etc/uwsgi.d/databosch.ini', use_sudo=True)
put('mijndenbosch.ini', '/etc/uwsgi.d/mijndenbosch.ini', use_sudo=True)
put('nginx.conf', '/etc/nginx/conf.d/%s.conf' % project_name, use_sudo=True)

# Reload
print(red('\nReloading...', bold=True))
#sudo('systemctl reload uwsgi')
sudo('systemctl reload nginx')
run('systemctl status -n0 uwsgi')
run('systemctl status -ln3 nginx')
