# Generated by Django 3.1.1 on 2020-09-23 14:32

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entiteit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('tagline', models.TextField(blank=True, verbose_name='in één zin')),
                ('beschrijving', ckeditor.fields.RichTextField(blank=True)),
                ('emailadres', models.EmailField(blank=True, max_length=254)),
                ('telefoonnummer', models.CharField(blank=True, max_length=255)),
                ('locatie_naam', models.CharField(blank=True, max_length=255)),
                ('bezoekadres', models.TextField(blank=True)),
                ('opgericht', models.DateField(blank=True, null=True)),
                ('gewijzigd', models.DateTimeField(auto_now=True)),
                ('aangemaakt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'entiteiten',
                'ordering': ['titel'],
            },
        ),
        migrations.CreateModel(
            name='Entiteitsoort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'entiteitsoorten',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('type', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Persoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=255)),
                ('achternaam', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefoonnummer', models.CharField(blank=True, max_length=32)),
                ('beschrijving', ckeditor.fields.RichTextField(blank=True)),
                ('profielfoto', models.ImageField(blank=True, upload_to='')),
                ('gewijzigd', models.DateTimeField(auto_now=True)),
                ('aangemaakt', models.DateTimeField(auto_now_add=True)),
                ('sites', models.ManyToManyField(blank=True, related_name='personen', to='sites.Site')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'personen',
                'ordering': ['voornaam', 'achternaam'],
            },
        ),
        migrations.CreateModel(
            name='Relatiesoort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'relatiesoorten',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'participatierollen',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='TagGroep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'tag groepen',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('groep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='maakdenbosch.taggroep')),
            ],
            options={
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='SiteTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='sites.site')),
            ],
            options={
                'verbose_name': 'site-specifieke tag',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='SiteEntiteit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actief', models.BooleanField(default=True, help_text='Geef hiermee aan of deze entiteit zichtbaar is op deze site')),
                ('tagline', models.TextField(blank=True, help_text='Laat dit veld leeg om de algemene tagline te gebruiken')),
                ('beschrijving', ckeditor.fields.RichTextField(blank=True, help_text='Laat dit veld leeg om de algemene beschrijving te gebruiken')),
                ('entiteit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_entiteiten', to='maakdenbosch.entiteit')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_entiteiten', to='sites.site')),
                ('tags', models.ManyToManyField(blank=True, to='maakdenbosch.SiteTag', verbose_name='site-specifieke tags')),
            ],
            options={
                'verbose_name': 'site-specifieke beschrijving',
                'verbose_name_plural': 'site-specifieke beschrijvingen',
            },
        ),
        migrations.CreateModel(
            name='PersoonHyperlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperlinks', to='maakdenbosch.persoon')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maakdenbosch.linktype')),
            ],
        ),
        migrations.CreateModel(
            name='EntiteitVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('entiteit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='maakdenbosch.entiteit')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'video’s',
            },
        ),
        migrations.CreateModel(
            name='EntiteitRelatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naar_entiteit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaties_van', to='maakdenbosch.entiteit', verbose_name='entiteit')),
                ('soort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maakdenbosch.relatiesoort')),
                ('van_entiteit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaties_naar', to='maakdenbosch.entiteit', verbose_name='entiteit')),
            ],
            options={
                'verbose_name': 'relatie',
            },
        ),
        migrations.CreateModel(
            name='EntiteitParticipatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('entiteit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaties', to='maakdenbosch.entiteit')),
                ('persoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entiteit_participaties', to='maakdenbosch.persoon')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maakdenbosch.rol')),
            ],
            options={
                'verbose_name': 'participatie',
            },
        ),
        migrations.CreateModel(
            name='EntiteitHyperlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('entiteit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperlinks', to='maakdenbosch.entiteit')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maakdenbosch.linktype')),
            ],
            options={
                'verbose_name': 'hyperlink',
            },
        ),
        migrations.CreateModel(
            name='EntiteitFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestand', models.ImageField(upload_to='')),
                ('entiteit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='maakdenbosch.entiteit')),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'foto’s',
            },
        ),
        migrations.AddField(
            model_name='entiteit',
            name='sites',
            field=models.ManyToManyField(related_name='entiteiten', through='maakdenbosch.SiteEntiteit', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='entiteit',
            name='soort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maakdenbosch.entiteitsoort'),
        ),
        migrations.AddField(
            model_name='entiteit',
            name='tags',
            field=models.ManyToManyField(blank=True, to='maakdenbosch.Tag'),
        ),
    ]
