# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 14:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doelgroep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Doelgroepen',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestand', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'foto’s',
            },
        ),
        migrations.CreateModel(
            name='Hyperlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Website', 'Website'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Flickr', 'Flickr'), ('Other', 'Other')], max_length=16)),
                ('url', models.URLField(verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('omschrijving', ckeditor.fields.RichTextField(blank=True)),
                ('emailadres', models.EmailField(blank=True, max_length=254)),
                ('bezoekadres', models.TextField(blank=True)),
                ('mijndenbosch', models.BooleanField(default=False, verbose_name='Zichtbaar op MijnDenBosch.nl')),
                ('doelgroepen', models.ManyToManyField(blank=True, to='maakdenbosch.Doelgroep')),
            ],
            options={
                'verbose_name_plural': 'projecten',
                'ordering': ['titel'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['naam'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='maakdenbosch.Tag'),
        ),
        migrations.AddField(
            model_name='hyperlink',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperlinks', to='maakdenbosch.Project'),
        ),
        migrations.AddField(
            model_name='foto',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maakdenbosch.Project'),
        ),
    ]
