# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['naam'], 'verbose_name_plural': 'rollen'},
        ),
    ]
