# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0002_auto_20160414_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doelgroep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='doelgroepen',
            field=models.ManyToManyField(blank=True, to='maakdenbosch.Doelgroep'),
        ),
    ]
