# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 08:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0002_auto_20160512_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lange_beschrijving',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
