# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0003_auto_20160414_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doelgroep',
            options={'ordering': ['naam'], 'verbose_name_plural': 'Doelgroepen'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['naam']},
        ),
    ]
