# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0004_auto_20160512_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisatie',
            old_name='beschrijving',
            new_name='korte_beschrijving',
        ),
    ]
