# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 06:31
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0005_auto_20160520_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisatie',
            name='lange_beschrijving',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organisatie',
            name='korte_beschrijving',
            field=models.TextField(blank=True),
        ),
    ]
