# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('maakdenbosch', '0006_auto_20160520_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschrijving', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'site-specifieke beschrijvingen',
                'verbose_name': 'site-specifieke beschrijving',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='mijndenbosch',
        ),
        migrations.AddField(
            model_name='siteproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maakdenbosch.Project'),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='project',
            name='sites',
            field=models.ManyToManyField(related_name='projects', through='maakdenbosch.SiteProject', to='sites.Site'),
        ),
    ]
