# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 13:51
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0007_auto_20160607_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteproject',
            name='beschrijving',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
