# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0009_auto_20160607_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='lange_beschrijving',
            new_name='beschrijving',
        ),
    ]
