# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0010_auto_20160607_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyperlink',
            name='type',
            field=models.CharField(choices=[('Website', 'Website'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Flickr', 'Flickr'), ('LinkedIn', 'LinkedIn'), ('Droomstad', 'Droomstad'), ('Other', 'Other')], max_length=16),
        ),
    ]
