# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 09:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('maakdenbosch', '0011_auto_20160607_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteOrganisatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschrijving', ckeditor.fields.RichTextField(blank=True)),
                ('organisatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_organisaties', to='maakdenbosch.Organisatie')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_organisaties', to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'site-specifieke beschrijvingen',
                'verbose_name': 'site-specifieke beschrijving',
            },
        ),
    ]
