# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0012_siteorganisatie'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='korte_beschrijving',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteorganisatie',
            name='korte_beschrijving',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='korte_beschrijving',
            field=models.TextField(blank=True),
        ),
    ]
