# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0013_auto_20160609_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisatie',
            old_name='korte_beschrijving',
            new_name='tagline',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='korte_beschrijving',
            new_name='tagline',
        ),
        migrations.RenameField(
            model_name='siteorganisatie',
            old_name='korte_beschrijving',
            new_name='tagline',
        ),
        migrations.RenameField(
            model_name='siteproject',
            old_name='korte_beschrijving',
            new_name='tagline',
        ),
    ]
