# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0015_auto_20160609_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisatieHyperlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Website', 'Website'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Flickr', 'Flickr'), ('LinkedIn', 'LinkedIn'), ('Droomstad', 'Droomstad'), ('Other', 'Other')], max_length=16)),
                ('url', models.URLField(verbose_name='URL')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperlinks', to='maakdenbosch.Organisatie')),
            ],
        ),
    ]
