# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 11:15
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maakdenbosch', '0016_organisatiehyperlink'),
        ('mijndenbosch', '0023_auto_20160621_1303'),
    ]

    # Convert "operations" to only be "state_operations"
    state_operations = [
        # Theses migrations were auto-generated by Django makemigrations.
        migrations.CreateModel(
            name='Persoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(blank=True, max_length=255)),
                ('achternaam', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefoonnummer', models.CharField(blank=True, max_length=32)),
                ('beschrijving', ckeditor.fields.RichTextField(blank=True)),
                ('profielfoto', models.ImageField(blank=True, upload_to='')),
                ('aangemaakt', models.DateTimeField(auto_now_add=True)),
                ('sites', models.ManyToManyField(blank=True, related_name='personen', to='sites.Site')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['achternaam'],
                'verbose_name_plural': 'personen',
            },
        ),
        migrations.AlterField(
            model_name='participatie',
            name='persoon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participaties', to='maakdenbosch.Persoon'),
        ),
    ]

    operations = [
        # By running only state operations, we are making Django think it has
        # applied this migration to the database. In reality, we renamed a
        # "cars_tires" table to "tires_tires" earlier.
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
