# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 11:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0017_auto_20160621_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisatie',
            options={'ordering': ['naam']},
        ),
        migrations.AddField(
            model_name='organisatie',
            name='aangemaakt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 21, 11, 55, 23, 135192, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisatie',
            name='locatie',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='participatie',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='aangemaakt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 21, 11, 55, 30, 801710, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteproject',
            name='actief',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organisatie',
            name='bezoekadres',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organisatie',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organisatiehyperlink',
            name='type',
            field=models.CharField(choices=[('Website', 'Website'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Flickr', 'Flickr'), ('LinkedIn', 'LinkedIn'), ('Instagram', 'Instagram'), ('Youtube', 'Youtube'), ('Droomstad', 'Droomstad'), ('Other', 'Other')], max_length=16),
        ),
    ]
