# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0018_auto_20160621_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persoon',
            options={'ordering': ['voornaam', 'achternaam'], 'verbose_name_plural': 'personen'},
        ),
    ]
