# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0019_auto_20160621_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyperlink',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='organisatiehyperlink',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
