# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0021_auto_20160621_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyperlink',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maakdenbosch.LinkType'),
        ),
        migrations.AddField(
            model_name='organisatiehyperlink',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maakdenbosch.LinkType'),
        ),
    ]
