# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0022_auto_20160621_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyperlink',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maakdenbosch.LinkType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisatiehyperlink',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maakdenbosch.LinkType'),
            preserve_default=False,
        ),
    ]
