# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0023_auto_20160621_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteproject',
            name='actief',
        ),
    ]
