# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0024_remove_siteproject_actief'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteorganisatie',
            name='actief',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='actief',
            field=models.BooleanField(default=True),
        ),
    ]
