# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('maakdenbosch', '0025_auto_20160621_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisatie',
            name='sites',
            field=models.ManyToManyField(related_name='organisaties', through='maakdenbosch.SiteOrganisatie', to='sites.Site'),
        ),
    ]
