# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0026_organisatie_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bezoekadres',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
