# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0027_auto_20160621_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisatie',
            old_name='locatie',
            new_name='locatie_naam',
        ),
        migrations.AddField(
            model_name='project',
            name='locatie_naam',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
