# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0029_auto_20160622_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersoonHyperlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperlinks', to='maakdenbosch.Persoon')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maakdenbosch.LinkType')),
            ],
        ),
        migrations.AddField(
            model_name='organisatie',
            name='opgericht',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='opgericht',
            field=models.DateField(blank=True, null=True),
        ),
    ]
