# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 16:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0030_auto_20160627_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisatie',
            name='gewijzigd',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 27, 16, 48, 11, 244396, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persoon',
            name='gewijzigd',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 27, 16, 48, 16, 862027, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='gewijzigd',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 27, 16, 48, 23, 412484, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
