# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0032_auto_20160627_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taggroep',
            options={'ordering': ['naam'], 'verbose_name_plural': 'tag groepen'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='groep',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='maakdenbosch.TagGroep'),
            preserve_default=False,
        ),
    ]
