# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0033_auto_20160627_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='groep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maakdenbosch.TagGroep'),
        ),
    ]
