# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0036_auto_20160630_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisatie',
            name='doelgroepen',
        ),
        migrations.RemoveField(
            model_name='project',
            name='doelgroepen',
        ),
        migrations.DeleteModel(
            name='Doelgroep',
        ),
    ]
