# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0037_auto_20160630_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisatie',
            name='bezoekadres',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='bezoekadres',
            field=models.TextField(blank=True),
        ),
    ]
