# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0038_auto_20160711_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisatie',
            name='telefoonnummer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='telefoonnummer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
