# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0039_auto_20160711_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foto',
            new_name='ProjectFoto',
        ),
    ]
