# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0042_auto_20160802_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntiteitFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestand', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'foto’s',
            },
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['naam'], 'verbose_name_plural': 'participatierollen'},
        ),
        migrations.AddField(
            model_name='entiteit',
            name='relaties_naar',
            field=models.ManyToManyField(related_name='relaties_van', through='maakdenbosch.EntiteitRelatie', to='maakdenbosch.Entiteit'),
        ),
        migrations.AddField(
            model_name='entiteitfoto',
            name='entiteit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maakdenbosch.Entiteit'),
        ),
    ]
