# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0046_auto_20160802_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entiteitrelatie',
            name='naar_entiteit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaties_van', to='maakdenbosch.Entiteit'),
        ),
        migrations.AlterField(
            model_name='entiteitrelatie',
            name='van_entiteit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaties_naar', to='maakdenbosch.Entiteit'),
        ),
    ]
