# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0047_auto_20160802_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entiteitparticipatie',
            options={'verbose_name': 'participatie'},
        ),
        migrations.AlterModelOptions(
            name='entiteitrelatie',
            options={'verbose_name': 'relatie'},
        ),
        migrations.AlterField(
            model_name='entiteitrelatie',
            name='naar_entiteit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaties_van', to='maakdenbosch.Entiteit', verbose_name='entiteit'),
        ),
        migrations.AlterField(
            model_name='entiteitrelatie',
            name='van_entiteit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaties_naar', to='maakdenbosch.Entiteit', verbose_name='entiteit'),
        ),
    ]
