# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0049_data_migration_to_entiteiten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hyperlink',
            name='project',
        ),
        migrations.RemoveField(
            model_name='hyperlink',
            name='type',
        ),
        migrations.RemoveField(
            model_name='organisatie',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='organisatie',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='organisatiefoto',
            name='organisatie',
        ),
        migrations.RemoveField(
            model_name='organisatiehyperlink',
            name='project',
        ),
        migrations.RemoveField(
            model_name='organisatiehyperlink',
            name='type',
        ),
        migrations.RemoveField(
            model_name='participatie',
            name='organisatie',
        ),
        migrations.RemoveField(
            model_name='participatie',
            name='persoon',
        ),
        migrations.RemoveField(
            model_name='participatie',
            name='project',
        ),
        migrations.RemoveField(
            model_name='participatie',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='projectfoto',
            name='project',
        ),
        migrations.RemoveField(
            model_name='siteorganisatie',
            name='organisatie',
        ),
        migrations.RemoveField(
            model_name='siteorganisatie',
            name='site',
        ),
        migrations.RemoveField(
            model_name='siteproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='siteproject',
            name='site',
        ),
        migrations.DeleteModel(
            name='Hyperlink',
        ),
        migrations.DeleteModel(
            name='Organisatie',
        ),
        migrations.DeleteModel(
            name='OrganisatieFoto',
        ),
        migrations.DeleteModel(
            name='OrganisatieHyperlink',
        ),
        migrations.DeleteModel(
            name='Participatie',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectFoto',
        ),
        migrations.DeleteModel(
            name='SiteOrganisatie',
        ),
        migrations.DeleteModel(
            name='SiteProject',
        ),
    ]
