# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0049_data_migration_to_entiteiten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entiteit',
            name='titel',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
