# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-17 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0050_auto_20160802_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entiteit',
            options={'ordering': ['titel'], 'permissions': (('view_entiteit', 'Can view entiteit'),), 'verbose_name_plural': 'entiteiten'},
        ),
        migrations.AlterModelOptions(
            name='persoon',
            options={'ordering': ['voornaam', 'achternaam'], 'permissions': (('view_persoon', 'Can view persoon'),), 'verbose_name_plural': 'personen'},
        ),
    ]
