# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0051_auto_20160917_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entiteitfoto',
            name='entiteit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='maakdenbosch.Entiteit'),
        ),
    ]
