# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0052_auto_20161003_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntiteitVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('entiteit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='maakdenbosch.Entiteit')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'video’s',
            },
        ),
        migrations.AlterModelOptions(
            name='entiteitfoto',
            options={'verbose_name': 'foto', 'verbose_name_plural': 'foto’s'},
        ),
    ]
