# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-16 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('maakdenbosch', '0053_auto_20161003_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='sites.Site')),
            ],
            options={
                'verbose_name': 'site-specifieke tag',
                'ordering': ['naam'],
            },
        ),
        migrations.AlterField(
            model_name='siteentiteit',
            name='actief',
            field=models.BooleanField(default=True, help_text='Geef hier aan of deze entiteit zichtbaar is op deze site'),
        ),
        migrations.AddField(
            model_name='siteentiteit',
            name='tags',
            field=models.ManyToManyField(blank=True, to='maakdenbosch.SiteTag'),
        ),
    ]
