# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-20 12:10
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0054_auto_20161116_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteentiteit',
            name='actief',
            field=models.BooleanField(default=True, help_text='Geef hiermee aan of deze entiteit zichtbaar is op deze site'),
        ),
        migrations.AlterField(
            model_name='siteentiteit',
            name='beschrijving',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Laat dit veld leeg om de algemene beschrijving te gebruiken'),
        ),
        migrations.AlterField(
            model_name='siteentiteit',
            name='tagline',
            field=models.TextField(blank=True, help_text='Laat dit veld leeg om de algemene tagline te gebruiken'),
        ),
        migrations.AlterField(
            model_name='siteentiteit',
            name='tags',
            field=models.ManyToManyField(blank=True, to='maakdenbosch.SiteTag', verbose_name='site-specifieke tags'),
        ),
    ]
