# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0055_auto_20161120_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persoon',
            name='achternaam',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='persoon',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='persoon',
            name='voornaam',
            field=models.CharField(max_length=255),
        ),
    ]
