# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-08 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0056_auto_20161122_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='entiteit',
            name='slug',
            field=models.SlugField(help_text='Dit netwerk is te bezoeken op mijndenbosch.nl/netwerk/[watjijhierinvult]/', null=True, unique=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='entiteit',
            name='tagline',
            field=models.TextField(blank=True, verbose_name='in één zin'),
        ),
    ]
