# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-04 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0058_auto_20161216_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entiteit',
            name='slug',
        ),
    ]
