# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0059_remove_entiteit_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='linktype',
            name='icon',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
