# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0060_linktype_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linktype',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='linktype',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='positie'),
            preserve_default=False,
        ),
    ]
