# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-07 13:39
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.PositiveIntegerField(choices=[(1, 'Footer tekst')])),
                ('content', models.TextField(verbose_name='inhoud')),
            ],
            options={
                'verbose_name': 'Parameter',
                'ordering': ['parameter'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('menu', models.BooleanField(default=True, verbose_name='zichtbaar in het menu')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='afbeelding')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'Pagina’s',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('visibility', models.PositiveIntegerField(choices=[(1, 'Altijd zichtbaar'), (2, 'Alleen op desktop'), (3, 'Onzichtbaar')], default=1, verbose_name='zichtbaarheid')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='titel')),
                ('contents', ckeditor.fields.RichTextField(blank=True, verbose_name='inhoud')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='afbeelding')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, help_text='Plak hier een YouTube, Vimeo, of SoundCloud link')),
                ('button', models.CharField(blank=True, max_length=255, verbose_name='button')),
                ('hyperlink', models.URLField(blank=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='effect.Page', verbose_name='pagina')),
            ],
            options={
                'verbose_name': 'sectie',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('image', models.ImageField(upload_to='', verbose_name='afbeelding')),
                ('hyperlink', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Social Media',
                'ordering': ['position'],
            },
        ),
    ]
