# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-07 15:27
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0002_auto_20170807_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('name', models.CharField(max_length=255, verbose_name='naam')),
            ],
            options={
                'verbose_name': 'Locatie',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_in_timetable', models.BooleanField(verbose_name='zichtbaar in blokkenschema')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
                ('slug', models.SlugField()),
                ('tagline', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='beschrijving')),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='effect.Location', verbose_name='locatie')),
            ],
            options={
                'verbose_name_plural': 'Programmaonderdelen',
                'ordering': ['title'],
                'verbose_name': 'Programmaonderdeel',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='naam')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField(verbose_name='begintijd')),
                ('end', models.DateTimeField(verbose_name='eindtijd')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effect.Program')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='effect.Icon'),
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Normaal'), (2, 'Video'), (3, 'Nieuws klein'), (4, 'Nieuws groot'), (5, 'Projecten'), (6, 'Partners'), (7, 'Minisectie')], default=1, verbose_name='soort sectie'),
        ),
        migrations.AddField(
            model_name='program',
            name='tags',
            field=models.ManyToManyField(blank=True, to='effect.Tag'),
        ),
    ]
