# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0003_auto_20170807_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icon',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='icon',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='positie'),
            preserve_default=False,
        ),
    ]
