# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0004_auto_20170808_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='hyperlink',
        ),
        migrations.AddField(
            model_name='icon',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='naam'),
            preserve_default=False,
        ),
    ]
