# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0005_auto_20170821_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Naam'),
            preserve_default=False,
        ),
    ]
