# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0007_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['date'], 'verbose_name': 'Nieuwsbericht', 'verbose_name_plural': 'Nieuwsberichten'},
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='foto'),
        ),
    ]
