# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0059_remove_entiteit_slug'),
        ('effect', '0010_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maakdenbosch.Entiteit')),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title'], 'verbose_name_plural': 'Projecten'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.AddField(
            model_name='project',
            name='entity',
            field=models.ForeignKey(blank=True, help_text='Kies hier de DataBosch entiteit die dit project vertegenwoordigt', null=True, on_delete=django.db.models.deletion.CASCADE, to='maakdenbosch.Entiteit', verbose_name='bestaande entiteit'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships', to='effect.Project'),
        ),
    ]
