# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0011_auto_20170906_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='effect.Tag'),
        ),
    ]
