# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0012_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='effect.Project'),
        ),
    ]
