# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0059_remove_entiteit_slug'),
        ('effect', '0013_news_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramHyperlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperlinks', to='effect.Program')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maakdenbosch.LinkType')),
            ],
            options={
                'verbose_name': 'hyperlink',
            },
        ),
    ]
