# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0014_programhyperlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload hier een afbeelding voor de header', upload_to='', verbose_name='afbeelding'),
        ),
        migrations.AlterField(
            model_name='section',
            name='hyperlink',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
