# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0016_auto_20171002_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='image',
        ),
        migrations.AddField(
            model_name='page',
            name='header',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='effect.Header'),
            preserve_default=False,
        ),
    ]
