# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0017_auto_20171002_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('image', models.ImageField(upload_to='', verbose_name='high-res origineel')),
                ('caption', models.CharField(max_length=255, verbose_name='bijschrift')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='effect.Project')),
            ],
            options={
                'verbose_name': 'Foto',
                'ordering': ['position'],
            },
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Normaal'), (2, 'Video'), (4, 'Nieuws'), (5, 'Projecten'), (6, 'Partners'), (7, 'Foto')], default=1, verbose_name='soort sectie'),
        ),
    ]
