# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0018_auto_20171013_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnership',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='partnership',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='positie'),
            preserve_default=False,
        ),
    ]
