# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0059_remove_entiteit_slug'),
        ('effect', '0019_auto_20171023_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='maakdenbosch.Persoon', verbose_name='projectleider'),
        ),
    ]
