# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0021_project_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True, verbose_name='actief'),
        ),
    ]
