# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0022_project_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='mobile_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='effect.Header'),
        ),
    ]
