# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0023_page_mobile_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='mobile_header',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='effect.Header'),
            preserve_default=False,
        ),
    ]
