# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0024_auto_20171120_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name': 'Nieuwsbericht', 'verbose_name_plural': 'Nieuwsberichten'},
        ),
        migrations.RemoveField(
            model_name='projectphoto',
            name='caption',
        ),
    ]
