# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0026_sponsor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Fonds', 'verbose_name_plural': 'Fondsen'},
        ),
        migrations.AddField(
            model_name='section',
            name='show_partners',
            field=models.BooleanField(default=False, verbose_name='laat fondsen zien in partnersectie'),
        ),
        migrations.AddField(
            model_name='section',
            name='show_partnerships',
            field=models.BooleanField(default=False, verbose_name='laat alle projectpartners zien in partnersectie'),
        ),
        migrations.AddField(
            model_name='section',
            name='show_sponsors',
            field=models.BooleanField(default=False, verbose_name='laat sponsors zien in partnersectie'),
        ),
    ]
