# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0027_auto_20171127_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Normaal'), (2, 'Video'), (4, 'Nieuws'), (5, 'Projecten'), (6, 'Partners'), (7, 'Foto'), (8, 'Formulier')], default=1, verbose_name='soort sectie'),
        ),
    ]
