# Generated by Django 2.0.2 on 2018-02-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0028_auto_20171208_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='afbeelding'),
        ),
    ]
