# Generated by Django 2.0.2 on 2018-03-22 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0029_program_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='tagline',
        ),
        migrations.AlterField(
            model_name='program',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effect.Location', verbose_name='locatie'),
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Normaal'), (2, 'Video'), (4, 'Nieuws'), (5, 'Projecten'), (6, 'Partners'), (7, 'Foto'), (8, 'Formulier'), (9, 'Programma')], default=1, verbose_name='soort sectie'),
        ),
    ]
