# Generated by Django 2.0.2 on 2018-03-29 11:52

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0032_programphoto_programvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programhyperlink',
            options={'verbose_name': 'social media link'},
        ),
        migrations.RemoveField(
            model_name='programvideo',
            name='image',
        ),
        migrations.AddField(
            model_name='programvideo',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Plak hier een YouTube, Vimeo, of SoundCloud link'),
        ),
    ]
