# Generated by Django 2.0.2 on 2018-05-24 12:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effect', '0033_auto_20180329_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='actief'),
        ),
        migrations.AlterField(
            model_name='program',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='effect.Location', verbose_name='locatie'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='begin',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 9, 12, 0), verbose_name='begintijd'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 9, 12, 0), verbose_name='eindtijd'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='effect.Program'),
        ),
    ]
