# Generated by Django 3.1.1 on 2020-09-23 14:32

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import rauwkost.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maakdenbosch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.PositiveIntegerField(choices=[(1, 'Consent verzoek (cookiemelding)'), (2, 'Consent button 1'), (3, 'Consent button 2'), (10, 'Footer midden'), (11, 'Footer links'), (12, 'Footer rechts'), (20, 'Button kleur'), (25, 'Extra menu items'), (30, 'Extra CSS')], unique=True)),
                ('content', models.TextField(blank=True, verbose_name='inhoud')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='bestand')),
            ],
            options={
                'verbose_name': 'Parameter',
                'ordering': ['parameter'],
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='bestand')),
            ],
            options={
                'ordering': ['file'],
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='datum')),
                ('header', models.FileField(blank=True, upload_to='', verbose_name='header')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
                ('introduction', models.TextField(blank=True, verbose_name='introductie')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='beschrijving')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL')),
                ('address', models.TextField(blank=True, verbose_name='adres')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='buitenfoto')),
                ('photo_inside', models.ImageField(blank=True, upload_to='', verbose_name='binnenfoto')),
                ('directions', models.ImageField(blank=True, upload_to='', verbose_name='plattegrond')),
                ('logo', models.ImageField(blank=True, upload_to='', verbose_name='logo')),
                ('icon', models.ImageField(blank=True, upload_to='', verbose_name='icoon kleur')),
                ('iconbw', models.ImageField(blank=True, upload_to='', verbose_name='icoon zwart/wit')),
                ('color', models.PositiveIntegerField(choices=[(1, 'Groen'), (2, 'Oranje'), (3, 'Geel'), (4, 'Roze'), (5, 'Paars'), (6, 'Blauw'), (7, 'Turquoise'), (8, 'Grijs'), (9, 'Rood'), (10, 'Bruin')], verbose_name='kleur')),
            ],
            options={
                'verbose_name': 'Locatie',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('button', models.CharField(blank=True, max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, help_text='Plak hier een YouTube, Vimeo, of SoundCloud link')),
            ],
            options={
                'verbose_name': 'nieuwsbericht',
                'verbose_name_plural': 'nieuwsberichten (niet meer gebruiken!)',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('menu', models.BooleanField(default=True, verbose_name='zichtbaar in het menu')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'Pagina’s',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='actief')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
                ('tagline', models.CharField(max_length=255, verbose_name='ondertitel')),
                ('slug', models.SlugField(help_text='dit item komt beschikbaar op https://rauwkost.online/2020/[URL]/ (klik rechtsboven op "weergeven op website" om hier nu naar toe te gaan!)', verbose_name='URL')),
                ('thumbnail', models.ImageField(blank=True, upload_to='', verbose_name='thumbnail')),
                ('short_description', models.TextField(blank=True, verbose_name='korte beschrijving')),
                ('long_description', ckeditor.fields.RichTextField(blank=True, verbose_name='lange beschrijving')),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
                ('ticketlink', models.CharField(blank=True, max_length=1024)),
                ('edition', models.ForeignKey(default=rauwkost.models.getedition, on_delete=django.db.models.deletion.PROTECT, to='rauwkost.edition', verbose_name='editie')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='rauwkost.location', verbose_name='locatie')),
            ],
            options={
                'verbose_name': 'Programma item',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('name', models.CharField(max_length=255, verbose_name='naam')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL')),
                ('icon', models.ImageField(blank=True, upload_to='', verbose_name='icoon')),
            ],
            options={
                'verbose_name': 'soort',
                'verbose_name_plural': 'soorten',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, verbose_name='nummer')),
                ('name', rauwkost.models.VarCharField(verbose_name='naam')),
            ],
            options={
                'verbose_name': 'Teamnaam',
                'verbose_name_plural': 'Teamnamen',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', rauwkost.models.VarCharField()),
                ('icon', models.ImageField(upload_to='')),
                ('hyperlink', models.URLField()),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='naam')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='actief')),
                ('name', rauwkost.models.VarCharField(verbose_name='naam')),
                ('function', rauwkost.models.VarCharField(blank=True, verbose_name='functie')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', rauwkost.models.VarCharField(blank=True, help_text='dit nummer wordt niet op de site getoond', verbose_name='telefoonnummer')),
                ('description', models.TextField(blank=True, verbose_name='over jezelf')),
                ('photo_bw', models.ImageField(blank=True, upload_to='', verbose_name='foto zwart/wit')),
                ('photo_fc', models.ImageField(blank=True, upload_to='', verbose_name='foto kleur')),
                ('editions', models.ManyToManyField(related_name='_teammember_editions_+', to='rauwkost.Edition', verbose_name='edities')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rauwkost.role', verbose_name='team')),
            ],
            options={
                'verbose_name': 'Bendelid',
                'verbose_name_plural': 'Bendeleden',
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
                ('introduction', models.TextField(blank=True, verbose_name='introductie')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='beschrijving')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='foto')),
                ('directions', models.ImageField(blank=True, upload_to='', verbose_name='plattegrond')),
                ('logo', models.ImageField(blank=True, upload_to='', verbose_name='logo')),
                ('icon', models.ImageField(blank=True, upload_to='', verbose_name='icoon kleur')),
                ('iconbw', models.ImageField(blank=True, upload_to='', verbose_name='icoon zwart/wit')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublocations', to='rauwkost.location')),
            ],
            options={
                'verbose_name': 'Plek',
                'verbose_name_plural': 'Plekken',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('hyperlink', models.URLField(blank=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='maakdenbosch.linktype')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(5, 'Homepage'), (10, 'Normaal'), (20, 'Nieuws/Blog'), (30, 'Foto (met credits)')], default=10, verbose_name='soort sectie')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='inhoud')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='afbeelding')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, help_text='Plak hier een YouTube, Vimeo, of SoundCloud link')),
                ('button', models.CharField(blank=True, max_length=255, verbose_name='button')),
                ('hyperlink', models.CharField(blank=True, max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='rauwkost.page', verbose_name='pagina')),
            ],
            options={
                'verbose_name': 'sectie',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProgramVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='rauwkost.program')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'video’s',
            },
        ),
        migrations.CreateModel(
            name='ProgramTimeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=rauwkost.models.default_date, verbose_name='datum')),
                ('begin', models.TimeField(verbose_name='begintijd')),
                ('end', models.TimeField(verbose_name='eindtijd')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='rauwkost.program')),
            ],
            options={
                'verbose_name': 'timeslot',
                'verbose_name_plural': 'timeslots',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ProgramPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='afbeelding')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rauwkost.program')),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'foto’s',
            },
        ),
        migrations.CreateModel(
            name='ProgramPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Wanneer je deze beschrijving leeg laat, toont de website de algemene beschrijving van de entiteit', verbose_name='site-specifieke beschrijving')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='maakdenbosch.entiteit')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='rauwkost.program')),
            ],
            options={
                'verbose_name': 'partner',
                'verbose_name_plural': 'partners',
            },
        ),
        migrations.CreateModel(
            name='ProgramHyperlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperlinks', to='rauwkost.program')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='maakdenbosch.linktype')),
            ],
            options={
                'verbose_name': 'hyperlink',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='sublocation',
            field=models.ForeignKey(blank=True, help_text='Kies eerst een locatie voordat je hier een sublocatie kunt kiezen', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rauwkost.sublocation'),
        ),
        migrations.AddField(
            model_name='program',
            name='tags',
            field=models.ManyToManyField(blank=True, to='rauwkost.Tag'),
        ),
        migrations.AddField(
            model_name='program',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='rauwkost.programtype', verbose_name='soort'),
        ),
        migrations.CreateModel(
            name='LocationHyperlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperlinks', to='rauwkost.location')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='maakdenbosch.linktype')),
            ],
            options={
                'verbose_name': 'hyperlink',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='actief')),
                ('title', rauwkost.models.VarCharField(verbose_name='titel')),
                ('slug', models.SlugField(help_text='rauwkost.online/nieuws/[URL]', unique=True, verbose_name='URL')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='datum')),
                ('introduction', models.TextField(blank=True, verbose_name='introductie')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='inhoud')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='afbeelding')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, help_text='Plak hier een YouTube of Vimeo link')),
                ('button_text', rauwkost.models.VarCharField(blank=True, verbose_name='button text')),
                ('button_link', rauwkost.models.VarCharField(blank=True, verbose_name='button link')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='rauwkost.program', verbose_name='programma item')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
