# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 10:03
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maakdenbosch', '0061_auto_20171120_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.PositiveIntegerField(choices=[(10, 'Footer tekst')])),
                ('content', models.TextField(verbose_name='inhoud')),
            ],
            options={
                'ordering': ['parameter'],
                'verbose_name': 'Parameter',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
                ('address', models.TextField(verbose_name='adres')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='foto')),
                ('logo', models.ImageField(blank=True, upload_to='', verbose_name='logo')),
                ('icon', models.ImageField(blank=True, upload_to='', verbose_name='icoon')),
                ('color', models.PositiveIntegerField(choices=[(1, 'Kleur 1'), (2, 'Kleur 2'), (3, 'Kleur 3')], verbose_name='kleur')),
            ],
            options={
                'ordering': ['position'],
                'verbose_name': 'Locatie',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('menu', models.BooleanField(default=True, verbose_name='zichtbaar in het menu')),
            ],
            options={
                'ordering': ['position'],
                'verbose_name_plural': 'Pagina’s',
                'verbose_name': 'Pagina',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.TimeField(verbose_name='begintijd')),
                ('end', models.TimeField(verbose_name='eindtijd')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
                ('tagline', models.CharField(max_length=255, verbose_name='ondertitel')),
                ('slug', models.SlugField()),
                ('short_description', models.TextField(blank=True, verbose_name='korte beschrijving')),
                ('long_description', ckeditor.fields.RichTextField(blank=True, verbose_name='lange beschrijving')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rauwkost.Location', verbose_name='locatie')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'Programma item',
            },
        ),
        migrations.CreateModel(
            name='ProgramHyperlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperlinks', to='rauwkost.Program')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='maakdenbosch.LinkType')),
            ],
            options={
                'verbose_name': 'hyperlink',
            },
        ),
        migrations.CreateModel(
            name='ProgramPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='afbeelding')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rauwkost.Program')),
            ],
            options={
                'verbose_name_plural': 'foto’s',
                'verbose_name': 'foto',
            },
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='naam')),
            ],
            options={
                'verbose_name_plural': 'soorten',
                'verbose_name': 'soort',
            },
        ),
    ]
