# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programtype',
            options={'ordering': ['position'], 'verbose_name': 'soort', 'verbose_name_plural': 'soorten'},
        ),
        migrations.AddField(
            model_name='programtype',
            name='icon',
            field=models.ImageField(blank=True, upload_to='', verbose_name='icoon'),
        ),
        migrations.AddField(
            model_name='programtype',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='positie'),
            preserve_default=False,
        ),
    ]
