# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0003_auto_20171208_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='programtype',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='URL'),
        ),
    ]
