# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0004_programtype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='rauwkost.ProgramType', verbose_name='soort'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='rauwkost.Location', verbose_name='locatie'),
        ),
    ]
