# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0005_auto_20171208_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='programtype',
            name='color',
            field=models.PositiveIntegerField(choices=[(1, 'Groen'), (2, 'Oranje'), (3, 'Geel'), (4, 'Roze'), (5, 'Paars'), (6, 'Blauw'), (7, 'Turquoise'), (8, 'Grijs'), (9, 'Rood'), (10, 'Bruin')], default=1, verbose_name='kleur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='color',
            field=models.PositiveIntegerField(choices=[(1, 'Groen'), (2, 'Oranje'), (3, 'Geel'), (4, 'Roze'), (5, 'Paars'), (6, 'Blauw'), (7, 'Turquoise'), (8, 'Grijs'), (9, 'Rood'), (10, 'Bruin')], verbose_name='kleur'),
        ),
    ]
