# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0006_auto_20171210_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['begin'], 'verbose_name': 'Programma item'},
        ),
        migrations.AddField(
            model_name='program',
            name='active',
            field=models.BooleanField(default=True, verbose_name='actief'),
        ),
    ]
