# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 23:49
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0007_auto_20171210_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
