# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0008_program_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programtype',
            name='color',
        ),
    ]
