# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0009_remove_programtype_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='iconbw',
            field=models.ImageField(blank=True, upload_to='', verbose_name='icoon zwart/wit'),
        ),
        migrations.AlterField(
            model_name='location',
            name='icon',
            field=models.ImageField(blank=True, upload_to='', verbose_name='icoon kleur'),
        ),
    ]
