# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 20:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0013_auto_20171211_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
                ('contents', ckeditor.fields.RichTextField(blank=True, verbose_name='inhoud')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='afbeelding')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, help_text='Plak hier een YouTube, Vimeo, of SoundCloud link')),
                ('button', models.CharField(blank=True, max_length=255, verbose_name='button')),
                ('hyperlink', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['position'],
                'verbose_name': 'sectie',
            },
        ),
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.AddField(
            model_name='section',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='rauwkost.Page', verbose_name='pagina'),
        ),
    ]
