# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0014_auto_20171211_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='contents',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='section',
            name='button',
        ),
    ]
