# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0016_auto_20171212_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='image',
            field=models.FileField(blank=True, upload_to='', verbose_name='bestand'),
        ),
        migrations.AlterField(
            model_name='config',
            name='parameter',
            field=models.PositiveIntegerField(choices=[(10, 'Footer midden'), (11, 'Footer links'), (12, 'Footer rechts'), (20, 'Homepage header'), (30, 'Extra CSS')], unique=True),
        ),
    ]
