# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-25 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0017_auto_20171213_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'video’s',
                'verbose_name': 'video',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='', verbose_name='thumbnail'),
        ),
        migrations.AddField(
            model_name='programvideo',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='rauwkost.Program'),
        ),
    ]
