# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0061_auto_20171120_1630'),
        ('rauwkost', '0018_auto_20171225_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='maakdenbosch.LinkType')),
            ],
            options={
                'ordering': ['type'],
            },
        ),
    ]
