# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0019_socialmediaicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaicon',
            name='hyperlink',
            field=models.URLField(blank=True),
        ),
    ]
