# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0020_socialmediaicon_hyperlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmediaicon',
            options={},
        ),
    ]
