# Generated by Django 2.0.2 on 2018-02-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0021_auto_20180118_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmediaicon',
            options={'ordering': ['pk']},
        ),
    ]
