# Generated by Django 2.0.2 on 2018-03-22 14:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0022_auto_20180208_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'nieuwsbericht',
                'verbose_name_plural': 'nieuwsberichten',
            },
        ),
    ]
