# Generated by Django 2.0.2 on 2018-03-22 14:44

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0023_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Plak hier een YouTube, Vimeo, of SoundCloud link'),
        ),
    ]
