# Generated by Django 2.0.2 on 2018-03-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0024_auto_20180322_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='type',
            field=models.PositiveIntegerField(choices=[(10, 'Normaal'), (20, 'Nieuwsberichten')], default=10, verbose_name='soort sectie'),
        ),
    ]
