# Generated by Django 2.0.2 on 2018-03-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0025_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='button',
            field=models.CharField(blank=True, max_length=255, verbose_name='button'),
        ),
    ]
