# Generated by Django 2.0.2 on 2018-10-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0026_section_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='year',
            field=models.PositiveIntegerField(default=2018, verbose_name='programmajaar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='config',
            name='parameter',
            field=models.PositiveIntegerField(choices=[(1, 'Programmajaar'), (10, 'Footer midden'), (11, 'Footer links'), (12, 'Footer rechts'), (20, 'Homepage header'), (30, 'Extra CSS')], unique=True),
        ),
    ]
