# Generated by Django 2.0.2 on 2018-10-01 14:28

import datetime
from django.db import migrations

def create_first_edition(apps, schema_editor):
    Edition = apps.get_model('rauwkost', 'Edition')
    try:
        Edition.objects.get(pk=1)
    except Edition.DoesNotExist:
        Edition(date=datetime.date(2018, 1, 27)).save()

class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0028_auto_20181001_1628'),
    ]

    operations = [
        migrations.RunPython(create_first_edition, migrations.RunPython.noop),
    ]
