# Generated by Django 2.0.2 on 2018-10-01 14:42

from django.db import migrations, models
import django.db.models.deletion
import rauwkost.models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0029_auto_20181001_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='year',
        ),
        migrations.AddField(
            model_name='program',
            name='edition',
            field=models.ForeignKey(default=rauwkost.models.getedition, on_delete=django.db.models.deletion.PROTECT, to='rauwkost.Edition', verbose_name='editie'),
        ),
    ]
