# Generated by Django 2.0.2 on 2018-10-03 12:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0031_auto_20181003_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpartner',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='site-specifieke beschrijving'),
        ),
    ]
