# Generated by Django 2.0.2 on 2018-10-03 12:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0032_programpartner_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='beschrijving'),
        ),
        migrations.AlterField(
            model_name='programpartner',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Wanneer je deze beschrijving leeg laat, toont de website de algemene beschrijving van de entiteit', verbose_name='site-specifieke beschrijving'),
        ),
    ]
