# Generated by Django 2.0.2 on 2019-08-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0035_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
