# Generated by Django 2.0.2 on 2019-08-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0036_newsitem_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='naam')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='tags',
            field=models.ManyToManyField(blank=True, to='rauwkost.Tag'),
        ),
    ]
