# Generated by Django 2.0.2 on 2019-10-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0037_auto_20190830_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='button',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
