# Generated by Django 2.0.2 on 2019-11-13 09:04

from django.db import migrations, models
import rauwkost.models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0038_newsitem_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', rauwkost.models.VarCharField()),
                ('photo_bw', models.ImageField(blank=True, upload_to='')),
                ('photo_fc', models.ImageField(blank=True, upload_to='')),
                ('editions', models.ManyToManyField(related_name='_teammember_editions_+', to='rauwkost.Edition')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
