# Generated by Django 2.0.2 on 2019-11-20 10:05

import ckeditor.fields
import datetime
from django.db import migrations, models
import embed_video.fields
import rauwkost.models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0039_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', rauwkost.models.VarCharField(verbose_name='titel')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='datum')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='inhoud')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='afbeelding')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, help_text='Plak hier een YouTube of Vimeo link')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.PositiveIntegerField(choices=[(5, 'Homepage'), (10, 'Normaal'), (20, 'Nieuwsberichten')], default=10, verbose_name='soort sectie'),
        ),
    ]
