# Generated by Django 2.0.2 on 2019-11-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0040_auto_20191120_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='introductie'),
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.PositiveIntegerField(choices=[(5, 'Homepage'), (10, 'Normaal'), (20, 'Nieuws/Blog')], default=10, verbose_name='soort sectie'),
        ),
    ]
