# Generated by Django 2.0.2 on 2019-11-22 12:45

from django.db import migrations, models
import django.db.models.deletion
import rauwkost.models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0041_auto_20191120_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-date'], 'verbose_name': 'nieuwsbericht', 'verbose_name_plural': 'nieuwsberichten (niet meer gebruiken!)'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['name'], 'verbose_name': 'Bendelid', 'verbose_name_plural': 'Bendeleden'},
        ),
        migrations.AddField(
            model_name='blog',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='rauwkost.Program', verbose_name='programma item'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(help_text='rauwkost.online/nieuws/[URL]', unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='config',
            name='parameter',
            field=models.PositiveIntegerField(choices=[(1, 'Consent verzoek (cookiemelding)'), (2, 'Consent button tekst'), (10, 'Footer midden'), (11, 'Footer links'), (12, 'Footer rechts'), (25, 'Extra menu items'), (30, 'Extra CSS')], unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='editions',
            field=models.ManyToManyField(related_name='_teammember_editions_+', to='rauwkost.Edition', verbose_name='edities'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=rauwkost.models.VarCharField(verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo_bw',
            field=models.ImageField(blank=True, upload_to='', verbose_name='foto zwart/wit'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo_fc',
            field=models.ImageField(blank=True, upload_to='', verbose_name='foto kleur'),
        ),
    ]
