# Generated by Django 2.0.2 on 2019-11-27 15:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0044_blog_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
                ('introduction', models.TextField(blank=True, verbose_name='introductie')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='beschrijving')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='foto')),
                ('logo', models.ImageField(blank=True, upload_to='', verbose_name='logo')),
                ('icon', models.ImageField(blank=True, upload_to='', verbose_name='icoon kleur')),
                ('iconbw', models.ImageField(blank=True, upload_to='', verbose_name='icoon zwart/wit')),
            ],
            options={
                'verbose_name': 'Plek',
                'verbose_name_plural': 'Plekken',
                'ordering': ['position'],
            },
        ),
        migrations.RemoveField(
            model_name='program',
            name='sublocation',
        ),
        migrations.AddField(
            model_name='location',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='introductie'),
        ),
        migrations.AddField(
            model_name='location',
            name='photo_inside',
            field=models.ImageField(blank=True, upload_to='', verbose_name='binnenfoto'),
        ),
        migrations.AlterField(
            model_name='location',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='buitenfoto'),
        ),
        migrations.AlterField(
            model_name='program',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='rauwkost.Location', verbose_name='locatie'),
        ),
        migrations.AlterField(
            model_name='program',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='rauwkost.ProgramType', verbose_name='soort'),
        ),
        migrations.AddField(
            model_name='sublocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublocations', to='rauwkost.Location'),
        ),
    ]
