# Generated by Django 2.0.2 on 2019-12-04 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0045_auto_20191127_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='sublocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rauwkost.SubLocation'),
        ),
        migrations.AlterField(
            model_name='config',
            name='parameter',
            field=models.PositiveIntegerField(choices=[(1, 'Consent verzoek (cookiemelding)'), (2, 'Consent button tekst'), (10, 'Footer midden'), (11, 'Footer links'), (12, 'Footer rechts'), (20, 'Button kleur'), (25, 'Extra menu items'), (30, 'Extra CSS')], unique=True),
        ),
    ]
