# Generated by Django 2.0.2 on 2019-12-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0046_auto_20191204_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublocation',
            name='slug',
        ),
    ]
