# Generated by Django 2.0.2 on 2019-12-04 11:21

from django.db import migrations, models
import django.db.models.deletion
import rauwkost.models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0048_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', rauwkost.models.VarCharField(verbose_name='naam')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Rollen',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='function',
            field=rauwkost.models.VarCharField(blank=True, verbose_name='functie'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rauwkost.Role', verbose_name='rol'),
        ),
    ]
