# Generated by Django 2.0.2 on 2019-12-04 11:35

from django.db import migrations, models
import django.db.models.deletion
import rauwkost.models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0049_auto_20191204_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Teamnaam', 'verbose_name_plural': 'Teamnamen'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='description',
            field=models.TextField(blank=True, verbose_name='over jezelf'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=rauwkost.models.VarCharField(blank=True, help_text='dit nummer wordt niet op de site getoond', verbose_name='telefoonnummer'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rauwkost.Role', verbose_name='team'),
        ),
    ]
