# Generated by Django 2.0.2 on 2019-12-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0050_auto_20191204_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='active',
            field=models.BooleanField(default=True, verbose_name='actief'),
        ),
    ]
