# Generated by Django 2.0.2 on 2019-12-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0051_teammember_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['number'], 'verbose_name': 'Teamnaam', 'verbose_name_plural': 'Teamnamen'},
        ),
        migrations.AddField(
            model_name='role',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='nummer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(help_text='dit item komt beschikbaar op https://rauwkost.online/2020/[URL]/ (klik rechtsboven op "weergeven op website" om hier nu naar toe te gaan!)', verbose_name='URL'),
        ),
    ]
