# Generated by Django 2.0.2 on 2019-12-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0053_auto_20191209_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='directions',
            field=models.ImageField(blank=True, upload_to='', verbose_name='plattegrond'),
        ),
    ]
