# Generated by Django 2.0.2 on 2019-12-10 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maakdenbosch', '0061_auto_20171120_1630'),
        ('rauwkost', '0054_location_directions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationHyperlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperlinks', to='rauwkost.Location')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='maakdenbosch.LinkType')),
            ],
            options={
                'verbose_name': 'hyperlink',
            },
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['role', 'name'], 'verbose_name': 'Bendelid', 'verbose_name_plural': 'Bendeleden'},
        ),
        migrations.AlterField(
            model_name='program',
            name='sublocation',
            field=models.ForeignKey(blank=True, help_text='Kies eerst een locatie voordat je hier een sublocatie kunt kiezen', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rauwkost.SubLocation'),
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.PositiveIntegerField(choices=[(5, 'Homepage'), (10, 'Normaal'), (20, 'Nieuws/Blog'), (30, 'Foto (met credits)')], default=10, verbose_name='soort sectie'),
        ),
    ]
