# Generated by Django 2.0.2 on 2019-12-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0055_auto_20191210_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublocation',
            name='directions',
            field=models.ImageField(blank=True, upload_to='', verbose_name='plattegrond'),
        ),
        migrations.AlterField(
            model_name='config',
            name='parameter',
            field=models.PositiveIntegerField(choices=[(1, 'Consent verzoek (cookiemelding)'), (2, 'Consent button 1'), (3, 'Consent button 2'), (10, 'Footer midden'), (11, 'Footer links'), (12, 'Footer rechts'), (20, 'Button kleur'), (25, 'Extra menu items'), (30, 'Extra CSS')], unique=True),
        ),
    ]
