# Generated by Django 2.0.2 on 2020-01-22 15:46

from django.db import migrations, models
import django.db.models.deletion
import rauwkost.models


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0056_auto_20191213_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramTimeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=rauwkost.models.default_date, verbose_name='datum')),
                ('begin', models.TimeField(verbose_name='begintijd')),
                ('end', models.TimeField(verbose_name='eindtijd')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='rauwkost.Program')),
            ],
            options={
                'verbose_name': 'timeslot',
                'verbose_name_plural': 'timeslots',
            },
        ),
    ]
