# Generated by Django 2.0.2 on 2020-01-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rauwkost', '0058_auto_20200122_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['title'], 'verbose_name': 'Programma item'},
        ),
        migrations.AlterModelOptions(
            name='programtimeslot',
            options={'ordering': ['date'], 'verbose_name': 'timeslot', 'verbose_name_plural': 'timeslots'},
        ),
        migrations.RemoveField(
            model_name='program',
            name='begin',
        ),
        migrations.RemoveField(
            model_name='program',
            name='date',
        ),
        migrations.RemoveField(
            model_name='program',
            name='end',
        ),
    ]
